site_name: asis
theme:
  name: material
  feature:
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.sugget

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary:
      accent:
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: grey

      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
