site_name: Asis
repo_url: https://github.com/juanpablo91/Asis
repo_name: juanpablo91/Asis
theme:
  logo: assets/icon.png
  favicon: assets/icon.png
  name: material
  icon:
    repo: fontawesome/brands/github

  features:
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.sugget

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent:
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black

      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mod
extra:
  alternate:
    - name: en - English
      link: /en/
      lang: en
    - name: es - Espanol
      link: /es/
      lang: es

extra:
  homepage: https://asisai.co

markdown_extensions:
  - attr_list
  - md_in_html
